### ISSUE TITLE
SolarCity API

### ISSUE THREAD

**Issue by stephenjamieson** [the-mace/evtools#2]
https://github.com/the-mace/evtools/blob/b5d75376769ae10b96d3025702e426477e48bec2/solarcity.py#L26

Actually they do provide an API (https://api.solarcity.com/powerguide/Help/Example). While I don't know the client_id or client_secret (and I think it's for partners only), if you auth on the solarcity site the 
HTML response includes a json doc named "window.appConfig" which actually has a "Token" key value pair.

**Comment by the-mace** [comment]
That's interesting but they provide no contact information at all and say its only for partners.

I've reached out to them but I expect I won't hear back. Thanks for sharing the link.
